version: '2'
services:
  logstash:
    image: logstash:5.0.0-1
    container_name: dataportal-logs-to-elasticsearch
    volumes:
      - .:/config
      - /var/log/download_occurrences_logs:/var/log/download_occurrences_logs
    command: -f /config/dataportal-download-log.conf
